import type { Metadata } from "next";
import Link from "next/link";
import { Home } from "lucide-react";
import { Inter } from "next/font/google";

import { ThemeProvider } from "@/components/theme-provider";
import { ThemeSwitcher } from "@/components/theme-switcher";
import { Toaster } from "@/components/ui/toaster";
import { Button } from "@/components/ui/button";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <header className="container flex p-2">
            <Link href="/">
              <Button className="p-2" variant="outline">
                <Home />
              </Button>
            </Link>
            <ThemeSwitcher className="ml-auto" />
          </header>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
